### ISSUE TITLE
ftps support 

### ISSUE THREAD

**Issue by Dawninest** [ne0z/react-native-ftp#1]
Thanks god! nice work,I searched for the RN ftp plugin for some days.I can't wait to try it!

**Comment by tls6a** [comment]
nothing in rnftp.m for ios project! fuck!!

**Comment by Dawninest** [comment]
@tls6a 我做了个iOS的RN的FTP插件，有需要的话可以来用看
[react-native-ftp-iOS](https://github.com/Dawninest/react-native-ftp-iOS)
