### ISSUE TITLE
can not use in ios

### ISSUE THREAD

**Issue by donghuiqiu** [ne0z/react-native-ftp#11]

**Comment by ne0z** [comment]
Hi @donghuiqiu I am sorry that for now this library is not supported for IOS yet. Basically, I am not familiar with IOS programming.

**Comment by donghuiqiu** [comment]
> Hi @donghuiqiu I am sorry that for now this library is not supported for IOS yet. Basically, I am not familiar with IOS programming.

Thank you all the same
