### ISSUE TITLE
[!] There are multiple dependencies with different sources for `RNFtp` in `Podfile`: 

### ISSUE THREAD

**Issue by Yali07** [ne0z/react-native-ftp#15]
I'm trying to install react-native-ftp for my ios app but i'm getting the below error.

here are the steps i follwed,

1. npm install react-native-ftp --save

2. react-native link react-native-ftp 

3. cd ios && pod install

[!] There are multiple dependencies with different sources for `RNFtp` in `Podfile`:

- RNFtp (from `../node_modules/react-native-ftp/ios`)
- RNFtp (from `../node_modules/react-native-ftp`)

**Comment by juanky201271** [comment]
As you can see in others tickets... It's not implemented for ios.
