### ISSUE TITLE
Dont work on IOS

### ISSUE THREAD

**Issue by NgKhanh** [ne0z/react-native-ftp#2]
Are you sure it work on iOS, 'cause I just copy your code and it shows error

> ExceptionsManager.js:65 Cannot read property 'setup' of undefined

```
import FTP from 'react-native-ftp';

FTP.setup("MY IP",21) //Setup host
FTP.login("myusername","mypassword").then(
  (result)=>{
    FTP.list(".").then(
      (result)=>{
        console.log(result);
      }
    );
  },
  (error)=>{
    alert(error);
  }
)

```
 
P/s : I'm sure to run "react-native link react-native-ftp". I also checked xcode manual to see libRNFtp.a on Link Binary With Libraries

**Comment by ne0z** [comment]
Sorry this module only for android yet. I don't have apple device to build react native module for ios.
