### ISSUE TITLE
Method doesn't override error

### ISSUE THREAD

**Issue by cagsurgunu** [ne0z/react-native-ftp#3]
When i make react-native run-android to my project, i get follow error:

**:react-native-ftp:compileReleaseJavaWithJavac
:react-native-ftp:compileReleaseJavaWithJavac - is not incremental (e.g. outputs
 have changed, no previous execution, etc.).
C:\ekran\ekran\node_modules\react-native-ftp\android\src\main\java\com\reactlibr
ary\RNFtpPackage.java:19: error: method does not override or implement a method
from a supertype
    @Override
    ^
1 error
:react-native-ftp:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.**

**Comment by ne0z** [comment]
It is due to a React Native do something change..... so just remove @Override in RNFtpPackage.java (line 19)
