### ISSUE TITLE
react-native-ftp is not working in iOS.

### ISSUE THREAD

**Issue by divyangsolanki** [ne0z/react-native-ftp#7]
Hello,
I have tried this library and it is working fine in Android but it is not working in iOS.
Can you please help me to find the solution?

`import React, { Component } from 'react';`
`import { StyleSheet, View, Button } from 'react-native';`
`import FTP from 'react-native-ftp';`

`export default class App extends Component {`
  `onButtonpress() {`
    `FTP.setup("IP", 21) //Setup host`
    `FTP.login("username", "password").then(`
      `(result) => {`
        `FTP.list(".").then(`
          `(result) => {`
           ` console.log(result);`
          `}`
        `);`
     ` },`
     ` (error) => {`
        `alert(error);`
      `}`
    `)`
  `}`
  `render() {`
    `return (`
      `<View style={styles.container}>`
        `<Button onPress={this.onButtonpress.bind(this)} title="hi" />`
      `</View>`
    `);`
  `}`
`}`
`const styles = StyleSheet.create({`
  `container: {`
    `flex: 1,`
    `justifyContent: 'center',`
    `alignItems: 'center',`
    `backgroundColor: '#F5FCFF',`
  `},`
  `welcome: {`
    `fontSize: 20,`
    `textAlign: 'center',`
    `margin: 10,`
  `},`
  `instructions: {`
    `textAlign: 'center',`
    `color: '#333333',`
    `marginBottom: 5,`
`  },`
`});`

**Comment by rathierry** [comment]
Hi,
I have also used this library and **it does not even work in iOS**.
Can you help me to resolve it ? Thanks :)

**Comment by xdragon93** [comment]
The error you encountered is because of react-native-ftp functions are not available on iOS - they are not implemented.
As you can see in here:
https://github.com/ne0z/react-native-ftp/blob/master/ios/RNFtp.m
This file is not implemented.

**Comment by ne0z** [comment]
Sorry, currently this library is not supporting IOS because I am not familiar with IOS programming.

**Comment by xdragon93** [comment]
yeah, so I am trying to implement this module for iOS as well for my project.
If I have done successfully, I will let you know.

**Comment by ne0z** [comment]
Thank you @Jaekson for your help.

**Comment by matheuscuba** [comment]
@Jaekson any progress on your iOS implementation?
