### ISSUE TITLE
Can't download file.

### ISSUE THREAD

**Issue by shihabmvl** [ne0z/react-native-ftp#9]
I was trying to download a file. The file path is like `/downloads/manual.pdf`.
If I call `FTP.list('/downloads')` then it lists all the files from the directory.
But, if I call `FTP.downloadFile('/manual.pdf', '/downloads')` then it throws an exception which is No such file.

What am I doing wrong? Using latest React Native, latest Android.

**Comment by ne0z** [comment]
It should be like this `FTP.downloadFile("/downloads/manual.pdf","./mydownloaded.pdf")` please change `./mydownloaded.pdf` with where you will place the downloaded file.

**Comment by shihabmvl** [comment]
I guess second parameter has to be a directory not full file path.
Like this: `FTP.downloadFile("/downloads/manual.pdf", "/myfolder"`
